version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ec2-shutdown"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s94msy21x82f"
s3_prefix = "ec2-shutdown"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
