AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS SAM Starter template

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 30

Resources:
  TranscribeFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: transcriber.lambdaHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /transcribe
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - transcriber.ts

  GetSignedURLFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get-signed-url.lambdaHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get-signed-url
            Method: get

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - get-signed-url.ts
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts


